name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build auth-service
      run: |
        cd auth-service
        mvn -B package --file pom.xml
    
    - name: Build user-service
      run: |
        cd user-service
        mvn -B package --file pom.xml
    
    - name: Build email-service
      run: |
        cd email-service
        mvn -B package --file pom.xml
    
    - name: Run tests
      run: |
        cd auth-service && mvn test
        cd ../user-service && mvn test
        cd ../email-service && mvn test 